### ISSUE TITLE
Allow usage of MDI icons

### ISSUE THREAD

**Issue by NovaGL** [DavidFW1960/bom_forecast#4]
I understand that you are using your own icons for this repo and not the mdi icons, however can I suggest that you create a new attribute called entity_picture. This can use your icons and leave the icons attribute as original.

It helps this integration work more globally instead of just your use case.

**Comment by DavidFW1960** [comment]
The component ONLY uses MDI icons.
The Lovelace card and HA Templates will use any icon you want to use. My examples use the BOM Icons downloaded from BOM. Any user is free and able to use any Icons they want to use.

**Comment by NovaGL** [comment]
Could you at least look into my request. I've looked at your code and it doesn't do MDI icons.

`ICON_MAPPING` generates the wrong icons for home assistant

**Comment by DavidFW1960** [comment]
The Icon Mapping Generates NO icons at all. It maps the BOM condition (which is a number) to a description/state:
```
ICON_MAPPING = {
    '1': 'sunny',
    '2': 'clear',
    '3': 'partly-cloudy',
    '4': 'cloudy',
    '6': 'haze',
    '8': 'light-rain',
    '9': 'wind',
    '10': 'fog',
    '11': 'showers',
    '12': 'rain',
    '13': 'dust',
    '14': 'frost',
    '15': 'snow',
    '16': 'storm',
    '17': 'light-showers',
    '18': 'heavy-showers',
    '19': 'tropicalcyclone'
}
```
At the momeny right not the returned icon for my location is 11 which maps to showers and that is the state:
![image](https://user-images.githubusercontent.com/36390762/87216919-5eff1c80-c387-11ea-84ba-8b53b82e0529.png)

There is no mapping to an icon. That is done in Lovelace when you render this on a card. There you can use any icon you want to use. If it is returning the wrong icon for your use case then you should use a template sensor to render the correct one.
This component only works with BOM and I am using their conditions for the state. I won't be changing that to return something that maps to some mdi icon.

The only actual icons in the code are MDI icons
```
SENSOR_TYPES = {
    'max': ['air_temperature_maximum', 'Max Temp C', TEMP_CELSIUS, 'mdi:thermometer'],
    'min': ['air_temperature_minimum', 'Min Temp C', TEMP_CELSIUS, 'mdi:thermometer'],
    'chance_of_rain': ['probability_of_precipitation', 'Chance of Rain', '%',
                       'mdi:water-percent'],
    'possible_rainfall': ['precipitation_range', 'Possible Rainfall', 'mm',
                          'mdi:water'],
    'summary': ['precis', 'Summary', None, 'mdi:text'],
    'detailed_summary': ['forecast', 'Detailed Summary', None, 'mdi:text'],
    'uv_alert': ['uv_alert', 'UV Alert', None, 'mdi:weather-sunny'],
    'fire_danger': ['fire_danger', 'Fire Danger', None, 'mdi:fire'],
    'icon': ['forecast_icon_code', 'Icon', None, None]
}
```
You can see in the screenshot above no icon is being specified for the entities... it is only returning the state there where the state is a BOM code.

**Comment by NovaGL** [comment]
Interesting as I only made one change to your code and now I get this.
Can you explain what is going on then?

```
ICON_MAPPING = {
    '1': 'mdi:weather-sunny',
    '2': 'mdi:weather-night',
    '3': 'mdi:weather-partly-cloudy',
    '4': 'mdi:weather-cloudy',
    '6': 'mdi:weather-sunset',
    '8': 'mdi:weather-partly-rainy',
    '9': 'mdi:weather-windy',
    '10': 'mdi:weather-sunset',
    '11': 'mdi:weather-rainy',
    '12': 'mdi:weather-pouring',
    '13': 'mdi:weather-sunset',
    '14': 'mdi:snowflake-melt',
    '15': 'mdi:weather-snowy',
    '16': 'mdi:weather-lightning',
    '17': 'mdi:weather-light-showers',
    '18': 'mdi:weather-pouring',
    '19': 'mdi:weather-hurricane'
}

```

![image](https://user-images.githubusercontent.com/16315601/87217224-493f2680-c38a-11ea-8e1b-394084af9b7f.png)

Using this config

```
  - platform: bom_forecast
    product_id: IDV10450
    name: Melbourne
    forecast_days: 6
    rest_of_today: true
    friendly: true
    friendly_state_format: '{max}°C, {summary}'
    monitored_conditions:
      - 'max'
      - 'min'      
      - 'chance_of_rain'
      - 'possible_rainfall'
      - 'summary'
      - 'detailed_summary'
      - 'icon'
```

**Comment by DavidFW1960** [comment]
So icon is a monitored condition. It returns the ICON_MAPPING as the state for that icon. There will be an icon entity for every day as per the forecast_days.
So in my screenshot above, the state is showers (mapped from 11 like yours) for day_0 (today)

But I don't see the summary etc and other information in my screenshot above. Where did your screenshot come from? Which entity? (I see you have friendly: true whereas I use False)

You can of course edit the code if you want however I'd be inclined to use a Template sensor to set the icon if it was me. My BOM weather card uses that state to set the correct animated icon as well.
![image](https://user-images.githubusercontent.com/36390762/87217496-1a767f80-c38d-11ea-8d33-0c5869d4b078.png)

**Comment by NovaGL** [comment]
Summary must be when `friendly: true`
I haven't modified the sensor. I can see that you don't want to change your sensor, so we'll just leave the discussion there.
It's just its the only bom repo that shows in HACS so I thought this could be adapted to be used more globally.

**Comment by DavidFW1960** [comment]
I'm going to see if I can change the icon to your MDI ones when friendly is set to true. It should be possible if I can work out how to make conditions in python...

**Comment by oneseventhree** [comment]
Hi,
Do you have a list of all the MDI icons used and their descrption. Kind of like:
```
ICON_MAPPING = {
    '1': 'mdi:weather-sunny',
    '2': 'mdi:weather-night',
    '3': 'mdi:weather-partly-cloudy',
    '4': 'mdi:weather-cloudy',
    '6': 'mdi:weather-sunset',
    '8': 'mdi:weather-partly-rainy',
    '9': 'mdi:weather-windy',
    '10': 'mdi:weather-sunset',
    '11': 'mdi:weather-rainy',
    '12': 'mdi:weather-pouring',
    '13': 'mdi:weather-sunset',
    '14': 'mdi:snowflake-melt',
    '15': 'mdi:weather-snowy',
    '16': 'mdi:weather-lightning',
    '17': 'mdi:weather-light-showers',
    '18': 'mdi:weather-pouring',
    '19': 'mdi:weather-hurricane'
}
```

and is there mdi icons for BOM for:
partly-cloudy-night
fog
sleet
clear
night-clear

?

**Comment by oneseventhree** [comment]
> I'm going to see if I can change the icon to your MDI ones when friendly is set to true. It should be possible if I can work out how to make conditions in python...

Hi,
Do you have a list of all the MDI icons used and their descrption. Kind of like:
```
ICON_MAPPING = {
    '1': 'mdi:weather-sunny',
    '2': 'mdi:weather-night',
    '3': 'mdi:weather-partly-cloudy',
    '4': 'mdi:weather-cloudy',
    '6': 'mdi:weather-sunset',
    '8': 'mdi:weather-partly-rainy',
    '9': 'mdi:weather-windy',
    '10': 'mdi:weather-sunset',
    '11': 'mdi:weather-rainy',
    '12': 'mdi:weather-pouring',
    '13': 'mdi:weather-sunset',
    '14': 'mdi:snowflake-melt',
    '15': 'mdi:weather-snowy',
    '16': 'mdi:weather-lightning',
    '17': 'mdi:weather-light-showers',
    '18': 'mdi:weather-pouring',
    '19': 'mdi:weather-hurricane'
}
```

as I need icons for that this BOM component puts out for the below:
partly-cloudy-night
fog
sleet
clear
night-clear

? I need this for tileboard (https://github.com/resoai/TileBoard)

and lastly, do you have a list of all the "short text" desciption/states?

Thanks in advance!

**Comment by DavidFW1960** [comment]
This component had been deprecated and replaced with https://github.com/bremor/bureau_of_meteorology
