### ISSUE TITLE
The 'entity_id' option is deprecated, please remove it from your configuration

### ISSUE THREAD

**Issue by x-Felix** [DavidFW1960/bom_forecast#6]
Thanks for this amazing integration. Finally get it work. 
There's one warning in the HA log. 

Logger: homeassistant.components.template.sensor
Source: helpers/config_validation.py:752
Integration: template (documentation, issues)
First occurred: 2:56:35 PM (9 occurrences)
Last logged: 2:56:35 PM

The 'entity_id' option is deprecated, please remove it from your configuration

I believe this is due to entity_id is used in weather.yaml. Not sure how to remove entity_id in that template. Would you please help? Thanks.

**Comment by DavidFW1960** [comment]
Ok. I edited them out of the weather.yaml templates.

**Comment by x-Felix** [comment]
wow, this is really quick. All good now. 
Thank you very much.
